//
//  RandomNameGenerator.swift
//  ASAPPTest
//
//  Created by Mitchell Morgan on 11/2/16.
//  Copyright © 2016 asappinc. All rights reserved.
//

import UIKit

class RandomNameGenerator: NSObject {

    static var firstNames: [String] = [
        "Ricardo",
        "Hershel",
        "Leon",
        "Judson",
        "Stanford",
        "Myron",
        "Elijah",
        "Ned",
        "Tod",
        "Marshall",
        "Lee",
        "Eric",
        "Christoper",
        "Fred",
        "Filiberto",
        "Arnoldo",
        "Elvin",
        "Rodrigo",
        "Reginald",
        "Samuel",
        "Anthony",
        "Owen",
        "Garry",
        "Corey",
        "Ralph",
        "Landon",
        "Miquel",
        "Abraham",
        "Mike",
        "Kirby",
        "Kareem",
        "Jefferey",
        "Tyrell",
        "Ray",
        "Duncan",
        "Olen",
        "Earnest",
        "Michael",
        "Miguel",
        "Rusty",
        "Xavier",
        "Andrea",
        "Gonzalo",
        "Theodore",
        "Samual",
        "Dong",
        "Cameron",
        "Omer",
        "Hayden",
        "Jarrod",
        "Kimberlie",
        "Melvina",
        "Nichol",
        "Elin",
        "Millie",
        "Maire",
        "Kathi",
        "Dominque",
        "Myrna",
        "Kenyatta",
        "Amanda",
        "Danette",
        "Kandice",
        "Jeannie",
        "Vinnie",
        "Bobbye",
        "Sha",
        "Isobel",
        "Lizeth",
        "Alejandra",
        "Tressie",
        "Candace",
        "Floria",
        "Rosa",
        "Laurice",
        "Nicolasa",
        "Earlean",
        "Linette",
        "Lia",
        "Ruthanne",
        "Waneta",
        "Lita",
        "Hortencia",
        "Luciana",
        "Vernice",
        "Neva",
        "Ardella",
        "Renee",
        "Domonique",
        "Ashely",
        "Anamaria",
        "Yolonda",
        "Kittie",
        "Rosalva",
        "Dagmar",
        "Belva",
        "Dona",
        "Wenona",
        "Iesha",
        "Melita"
    ]
    
    class func firstName() -> String {
        let randomIndex = Int(arc4random_uniform(UInt32(firstNames.count)))
        return firstNames[randomIndex]
    }
}
