// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class Credentials;
@class ASAPPStyles;
@class UIViewController;

SWIFT_CLASS("_TtC5ASAPP5ASAPP")
@interface ASAPP : NSObject
+ (UIViewController * _Nonnull)createChatViewControllerWithCredentials:(Credentials * _Nonnull)credentials styles:(ASAPPStyles * _Nullable)styles;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;
@class UIColor;

SWIFT_CLASS("_TtC5ASAPP11ASAPPStyles")
@interface ASAPPStyles : NSObject
@property (nonatomic, strong) UIFont * _Nonnull messageFont;
@property (nonatomic, strong) UIFont * _Nonnull subheadFont;
@property (nonatomic, strong) UIFont * _Nonnull detailFont;
@property (nonatomic, strong) UIFont * _Nonnull inputFont;
@property (nonatomic, strong) UIFont * _Nonnull inputSendButtonFont;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor1;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor2;
@property (nonatomic, strong) UIColor * _Nonnull foregroundColor1;
@property (nonatomic, strong) UIColor * _Nonnull foregroundColor2;
@property (nonatomic, strong) UIColor * _Nonnull separatorColor1;
@property (nonatomic, strong) UIColor * _Nonnull separatorColor2;
@property (nonatomic, strong) UIColor * _Nonnull messageFillColor;
@property (nonatomic, strong) UIColor * _Nullable messageStrokeColor;
@property (nonatomic, strong) UIColor * _Nonnull messageTextColor;
@property (nonatomic, strong) UIColor * _Nonnull replyMessageFillColor;
@property (nonatomic, strong) UIColor * _Nullable replyMessageStrokeColor;
@property (nonatomic, strong) UIColor * _Nonnull replyMessageTextColor;
@property (nonatomic, strong) UIColor * _Nonnull inputBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull inputBorderTopColor;
@property (nonatomic, strong) UIColor * _Nonnull inputTintColor;
@property (nonatomic, strong) UIColor * _Nonnull inputPlaceholderColor;
@property (nonatomic, strong) UIColor * _Nonnull inputTextColor;
@property (nonatomic, strong) UIColor * _Nonnull inputSendButtonColor;
@property (nonatomic, strong) UIColor * _Nonnull inputImageButtonColor;
+ (ASAPPStyles * _Nonnull)darkStyles;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ASAPP11Credentials")
@interface Credentials : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull companyMarker;
@property (nonatomic, readonly) BOOL isCustomer;
@property (nonatomic, readonly, copy) NSString * _Nullable userToken;
@property (nonatomic, readonly, copy) NSString * _Nullable targetCustomerToken;
- (nonnull instancetype)initWithCompany:(NSString * _Nonnull)company userToken:(NSString * _Nullable)userToken isCustomer:(BOOL)isCustomer targetCustomerToken:(NSString * _Nullable)targetCustomerToken OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@end


@interface NSDate (SWIFT_EXTENSION(ASAPP))
@end


@interface UIImage (SWIFT_EXTENSION(ASAPP))
@end

#pragma clang diagnostic pop
