# .circleci/config.yml

version: 2

jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    working_directory: /Users/distiller/output
    environment:
      XCODE_SCHEME: Tests
      XCODE_WORKSPACE: SDK/ASAPP.xcworkspace
    shell: /bin/bash --login -o pipefail
    steps:
      - run:
          name: Set Time Zone
          command: |
            sudo systemsetup -settimezone "America/New_York"
      - run:
          name: Pre-start simulator
          command: xcrun simctl boot "iPhone SE" || true
      - restore_cache:
          key: v6-homebrew-swiftlint
      - run:
          name: Install SwiftLint
          command: brew install swiftlint
      - save_cache:
          key: v6-homebrew-swiftlint
          paths:
            - /usr/local/Homebrew
      - add_ssh_keys:
          fingerprints:
            - "2a:d0:83:45:1c:03:01:c1:65:a0:48:8c:d9:ae:7e:61"
      - checkout
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems-
      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - v4-carthage-{{ checksum "SDK/Cartfile.resolved" }}
            - v4-carthage-
      - run:
          name: Carthage update
          command: ( cd SDK && carthage update --cache-builds --platform ios )
      - save_cache:
          key: v4-carthage-{{ checksum "SDK/Cartfile.resolved" }}
          paths:
            - SDK/Carthage/Build
      - run:
          name: Fastlane
          command: bundle exec fastlane test
      - run:
          command: |
            mkdir -p ./scan
            cp ./fastlane/test_output/report.junit ./scan/results.xml
            mkdir -p ./FailureDiffs
            [ -d SDK/Tests/UI\ Tests/FailureDiffs ] && mv SDK/Tests/UI\ Tests/FailureDiffs/* ./FailureDiffs || true
          when: always
      - store_test_results:
          path: ./scan
      - store_artifacts:
          path: ./FailureDiffs

  fastlane-beta:
    macos:
      xcode: "9.4.1"
    working_directory: /Users/distiller/output
    environment:
      XCODE_SCHEME: ASAPPTest
      XCODE_WORKSPACE: SDK/ASAPP.xcworkspace
    shell: /bin/bash --login -o pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2a:d0:83:45:1c:03:01:c1:65:a0:48:8c:d9:ae:7e:61"
      - checkout
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems-
      - run:
          name: Bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane
          command: bundle exec fastlane beta
      - store_artifacts:
          path: ../Library/Logs/gym/ASAPPTest-ASAPPTest.log
          destination: gym
      - store_artifacts:
          path: ./build/ASAPPTest.ipa
          destination: ipa
      - store_artifacts:
          path: ./build/ASAPPTest.app.dSYM.zip
          destination: dSYM

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - master
  deploy-beta:
    jobs:
      - fastlane-beta:
          filters:
            branches:
              only:
                - master

