# .circleci/config.yml

version: 2

jobs:
  fastlane-beta:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/output
    environment:
      XCODE_SCHEME: ASAPPTest
      XCODE_WORKSPACE: SDK/ASAPP.xcworkspace
      GYM_CODE_SIGNING_IDENTITY: 'iPhone Distribution: ASAPP Inc.'
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems-
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
            BUNDLE_PATH: vendor/bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Fastlane
          command: bundle exec fastlane beta
      - store_artifacts:
          path: ./ASAPPTest.ipa
          destination: ipa

workflows:
  version: 2
  deploy-beta:
    jobs:
      - fastlane-beta:
          filters:
            branches:
              only: master

