# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'ComcastTech' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 0.15.0'

end
