fastlane_version "2.58.0"

default_platform :ios

platform :ios do
  before_all do
    ENV['GYM_WORKSPACE'] = "SDK/ASAPP.xcworkspace"
  end

  lane :incrementBuildNumber do
    increment_build_number

    commit_version_bump(message: "increment build number")

    push_to_git_remote
  end

  lane :beta do
    incrementBuildNumber

    gym(scheme: 'ASAPPTest')

    crashlytics(
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      groups: ['asapp'],
      notes: changelog_from_git_commits,
      notifications: true
    )
  end
end
