fastlane_version "2.64.0"

default_platform :ios

platform :ios do
  before_all do
    ENV['GYM_WORKSPACE'] = "SDK/ASAPP.xcworkspace"
    TEST_APP_PROJECT = "SDK/ASAPPTest/ASAPPTest.xcodeproj"
  end

  lane :test do
    scan
  end

  lane :incrementBuildNumber do
    ensure_git_status_clean

    increment_build_number(xcodeproj: TEST_APP_PROJECT)

    commit_version_bump(
      message: "increment build number [skip ci]",
      xcodeproj: TEST_APP_PROJECT
    )
  end

  lane :beta do
    incrementBuildNumber

    gym(scheme: 'ASAPPTest')

    crashlytics(
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      groups: ['asapp'],
      notes: changelog_from_git_commits,
      notifications: true
    )

    # copy IPA so CircleCI can save it as an artifact"
    sh "mkdir -p ~/output/build"
    sh 'cp "$IPA_OUTPUT_PATH" ~/output/build/'
    
    clean_build_artifacts

    add_git_tag(grouping: "fastlane-builds")

    # push build number commit and new tag to master
    push_to_git_remote

    # update develop
    sh "git checkout develop"
    sh "git pull origin develop"
    sh "git merge --ff-only master"
    sh "git push origin develop"
  end

  lane :alpha do
    current_branch = git_branch
    UI.user_error!("The current branch is #{current_branch}. An alpha release should only be done from a feature branch.") if ["master", "develop"].include?(current_branch)

    incrementBuildNumber

    gym(scheme: 'ASAPPTest')

    crashlytics(
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      groups: ['asapp-ios-alpha'],
      notes: changelog_from_git_commits,
      notifications: true
    )

    clean_build_artifacts

    add_git_tag(grouping: "fastlane-builds")

    # push build number commit and new tag to remote
    push_to_git_remote(local_branch: current_branch)
  end

  lane :accessibility_testing do
    current_branch = git_branch
    UI.user_error!("The current branch is #{current_branch}. An alpha release should only be done from a feature branch.") if ["master", "develop"].include?(current_branch)

    incrementBuildNumber

    gym(scheme: 'ASAPPTest')

    crashlytics(
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      groups: ['accessibility-testing'],
      notes: changelog_from_git_commits,
      notifications: true
    )

    clean_build_artifacts

    add_git_tag(grouping: "fastlane-builds")

    # push build number commit and new tag to remote
    push_to_git_remote(local_branch: current_branch)
  end
end
