fastlane_version "2.60.1"

default_platform :ios

platform :ios do
  before_all do
    ENV['GYM_WORKSPACE'] = "SDK/ASAPP.xcworkspace"
    TEST_APP_PROJECT = "SDK/ASAPPTest/ASAPPTest.xcodeproj"
  end

  lane :incrementBuildNumber do
    clean_build_artifacts

    ensure_git_status_clean

    increment_build_number(xcodeproj: TEST_APP_PROJECT)

    commit_version_bump(
      message: "increment build number",
      xcodeproj: TEST_APP_PROJECT
    )

    push_to_git_remote
  end

  lane :beta do
    gym(scheme: 'ASAPPTest')

    crashlytics(
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      groups: ['asapp'],
      notes: changelog_from_git_commits,
      notifications: true
    )

    incrementBuildNumber

    add_git_tag(grouping: "fastlane-builds")

    push_git_tags
  end
end
