# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

workspace 'ASAPP'

target 'ASAPP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ASAPP
  pod 'SnapKit', '~> 0.21.1'
  pod 'RealmSwift', '~> 1.0.2'
  pod 'SocketRocket', '~> 0.5.1'
  pod 'SDWebImage', '~> 3.8.1'
  project 'ASAPP.xcodeproj'

end

target 'ASAPPTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ASAPPTest
  pod 'SnapKit', '~> 0.21.1'
  pod 'RealmSwift', '~> 1.0.2'
  pod 'SocketRocket', '~> 0.5.1'
  pod 'SDWebImage', '~> 3.8.1'
  project 'ASAPPTest/ASAPPTest.xcodeproj'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
