disabled_rules:
  - unused_optional_binding
  - trailing_comma
  - trailing_whitespace
  - notification_center_detachment
  - line_length
  - mark
  - identifier_name
  - large_tuple
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length

force_cast: warning

excluded:
  - 'ASAPP/Embedded Third-Party Code'
  - Carthage

