disabled_rules:
  - trailing_whitespace
  - notification_center_detachment
  - line_length
  - mark
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length

force_cast: warning

excluded:
  - 'ASAPP/Embedded Third-Party Code'
  - Carthage

identifier_name:
  excluded:
    - x
    - y
    - z
    - id
    - in

nesting:
  type_level:
    warning: 3

