disabled_rules:
  - trailing_whitespace
  - notification_center_detachment
  - line_length
  - mark
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length

force_cast: warning

excluded:
  - 'ASAPP/Embedded Third-Party Code'
  - Carthage

identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - x
    - y
    - z
    - id
    - in
    - i
    - j
    - k
    - a
    - r
    - g
    - b

nesting:
  type_level:
    warning: 3

